/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Health */
    get: operations["health_api_health_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/runs": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Runs */
    get: operations["runs_api_runs_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/runs/{run_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Run */
    get: operations["run_api_runs__run_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/runs/{run_id}/samples": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Samples */
    get: operations["samples_api_runs__run_id__samples_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/runs/{run_id}/samples/{sample_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Sample */
    get: operations["sample_api_runs__run_id__samples__sample_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/runs/{run_id}/artifacts/{path}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Artifact */
    get: operations["artifact_api_runs__run_id__artifacts__path__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/runs/{run_id}/views": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Views */
    get: operations["views_api_runs__run_id__views_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/compare": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Compare */
    get: operations["compare_api_compare_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/vectors": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Vectors */
    get: operations["vectors_api_vectors_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/experiments": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Experiments */
    get: operations["experiments_api_experiments_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/playground": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Info */
    get: operations["info_api_playground_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/playground/generate": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Generate */
    post: operations["generate_api_playground_generate_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/playground/inspect": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Inspect */
    post: operations["inspect_api_playground_inspect_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** Artifact */
    Artifact: {
      /** Path */
      path: string;
      /** Size */
      size: number | null;
    };
    /** Comparison */
    Comparison: {
      /** A */
      a: string;
      /** B */
      b: string;
      /** Only A */
      only_a: number;
      /** Only B */
      only_b: number;
      /** Scores */
      scores: components["schemas"]["PairedScore"][];
    };
    /**
     * Direction
     * @description Where a direction came from and what it is, stored alongside its values.
     */
    Direction: {
      /** Name */
      name: string;
      /** Model */
      model: string;
      /** Layer */
      layer: number;
      /** Method */
      method: string;
      /** Norm */
      norm: number;
      /** Dim */
      dim: number;
      /**
       * Created
       * Format: date-time
       */
      created: string;
      /** Run */
      run?: string | null;
      /** Notes */
      notes?: string | null;
    };
    /** Experiment */
    Experiment: {
      /** Name */
      name: string;
      /** Question */
      question: string | null;
      /** Runs */
      runs: components["schemas"]["RunSummary"][];
    };
    /** GenerateRequest */
    GenerateRequest: {
      /** Prompt */
      prompt: string;
      /**
       * Interventions
       * @default []
       */
      interventions: {
        [key: string]: unknown;
      }[];
      /**
       * Max New Tokens
       * @default 64
       */
      max_new_tokens: number;
    };
    /** GenerateResponse */
    GenerateResponse: {
      /** Text */
      text: string;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /** Health */
    Health: {
      /** Status */
      status: string;
      /** Version */
      version: string;
      /** Home */
      home: string;
    };
    /** HeatmapView */
    HeatmapView: {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      kind: "heatmap";
      /** Title */
      title: string;
      /** X */
      x: string[];
      /** Y */
      y: string[];
      /** Z */
      z: number[][];
      /** X Label */
      x_label: string;
      /** Y Label */
      y_label: string;
      /** Note */
      note?: string | null;
      /** Slices */
      slices?: {
        [key: string]: number[][];
      } | null;
      /** Labels */
      labels?: string[][] | null;
    };
    /** InspectRequest */
    InspectRequest: {
      /** Prompt */
      prompt: string;
      /**
       * Interventions
       * @default []
       */
      interventions: {
        [key: string]: unknown;
      }[];
      /**
       * Vectors
       * @description Saved directions to read, each at its own layer.
       * @default []
       */
      vectors: string[];
      /**
       * Chat
       * @description Wrap the prompt in the model's chat template.
       * @default true
       */
      chat: boolean;
    };
    /** InspectResponse */
    InspectResponse: {
      /** Views */
      views: (
        | components["schemas"]["HeatmapView"]
        | components["schemas"]["LineView"]
        | components["schemas"]["TableView"]
        | components["schemas"]["TokensView"]
      )[];
    };
    /** LineView */
    LineView: {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      kind: "line";
      /** Title */
      title: string;
      /** X */
      x: number[];
      /** Series */
      series: {
        [key: string]: number[];
      };
      /** X Label */
      x_label: string;
      /** Y Label */
      y_label: string;
      /** Note */
      note?: string | null;
    };
    /** Message */
    Message: {
      /** Role */
      role: string;
      /** Text */
      text: string;
      /** Tool Calls */
      tool_calls: components["schemas"]["ToolCall"][];
      /**
       * Tool Call Id
       * @description On a tool result: the call it answers.
       */
      tool_call_id?: string | null;
      /** Function */
      function?: string | null;
      /**
       * Error
       * @description On a tool result: the tool's error.
       */
      error?: string | null;
    };
    /** MetricPoint */
    MetricPoint: {
      /** Step */
      step: number;
      /** Value */
      value: number;
    };
    /** PairedScore */
    PairedScore: {
      /** Name */
      name: string;
      /** N */
      n: number;
      /** Mean A */
      mean_a: number;
      /** Mean B */
      mean_b: number;
      /**
       * Diff
       * @description Mean of B minus A over paired samples.
       */
      diff: number;
      /**
       * Low
       * @description 95% paired bootstrap interval of diff.
       */
      low: number;
      /** High */
      high: number;
      /**
       * Up
       * @description Samples where B scored higher.
       */
      up: number;
      /** Down */
      down: number;
    };
    /** PlaygroundInfo */
    PlaygroundInfo: {
      /** Model */
      model: string | null;
      /** Layers */
      layers: number | null;
    };
    /** RunDetail */
    RunDetail: {
      /** Id */
      id: string;
      /**
       * Kind
       * @enum {string}
       */
      kind: "eval" | "analysis" | "training";
      /** Name */
      name: string;
      /** Experiment */
      experiment: string | null;
      /** Status */
      status: string;
      /** Created */
      created: string | null;
      /** Model */
      model: string | null;
      /** Metrics */
      metrics: {
        [key: string]: number;
      };
      /** Samples */
      samples: number | null;
      /** Params */
      params: {
        [key: string]: string;
      };
      /** Tags */
      tags: {
        [key: string]: string;
      };
      /** History */
      history: {
        [key: string]: components["schemas"]["MetricPoint"][];
      };
      /** Artifacts */
      artifacts: components["schemas"]["Artifact"][];
      /** Scorers */
      scorers: string[];
      /** Error */
      error: string | null;
    };
    /** RunSummary */
    RunSummary: {
      /** Id */
      id: string;
      /**
       * Kind
       * @enum {string}
       */
      kind: "eval" | "analysis" | "training";
      /** Name */
      name: string;
      /** Experiment */
      experiment: string | null;
      /** Status */
      status: string;
      /** Created */
      created: string | null;
      /** Model */
      model: string | null;
      /** Metrics */
      metrics: {
        [key: string]: number;
      };
      /** Samples */
      samples: number | null;
    };
    /**
     * RunView
     * @description A figure a run logged under views/, addressed by its artifact path.
     */
    RunView: {
      /** Path */
      path: string;
      /** View */
      view:
        | components["schemas"]["HeatmapView"]
        | components["schemas"]["LineView"]
        | components["schemas"]["TableView"]
        | components["schemas"]["TokensView"];
    };
    /** SampleDetail */
    SampleDetail: {
      /** Id */
      id: string;
      /** Epoch */
      epoch: number;
      /** Target */
      target: string;
      /** Messages */
      messages: components["schemas"]["Message"][];
      /** Scores */
      scores: components["schemas"]["Score"][];
      /** Metadata */
      metadata: {
        [key: string]: string;
      };
      /** Error */
      error: string | null;
    };
    /** SampleSummary */
    SampleSummary: {
      /** Id */
      id: string;
      /** Epoch */
      epoch: number;
      /** Input */
      input: string;
      /** Target */
      target: string;
      /** Scores */
      scores: {
        [key: string]: number | null;
      };
      /** Error */
      error: string | null;
    };
    /** Score */
    Score: {
      /** Name */
      name: string;
      /** Value */
      value: number | null;
      /** Raw */
      raw: string;
      /** Answer */
      answer: string | null;
      /** Explanation */
      explanation: string | null;
    };
    /** TableView */
    TableView: {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      kind: "table";
      /** Title */
      title: string;
      /** Columns */
      columns: string[];
      /** Rows */
      rows: (string | number | boolean | null)[][];
      /** Note */
      note?: string | null;
      /** Links */
      links?: (string | null)[][] | null;
    };
    /** TokenRow */
    TokenRow: {
      /** Tokens */
      tokens: string[];
      /** Values */
      values: {
        [key: string]: number[];
      };
      /** Label */
      label?: string | null;
    };
    /** TokensView */
    TokensView: {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      kind: "tokens";
      /** Title */
      title: string;
      /** Rows */
      rows: components["schemas"]["TokenRow"][];
      /** Pairs */
      pairs?: {
        [key: string]: number[][];
      } | null;
      /** Note */
      note?: string | null;
    };
    /** ToolCall */
    ToolCall: {
      /**
       * Id
       * @default
       */
      id: string;
      /** Function */
      function: string;
      /**
       * Arguments
       * @description The arguments as indented JSON.
       */
      arguments: string;
      /** Parse Error */
      parse_error?: string | null;
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
      /** Input */
      input?: unknown;
      /** Context */
      ctx?: Record<string, never>;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  health_api_health_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Health"];
        };
      };
    };
  };
  runs_api_runs_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RunSummary"][];
        };
      };
    };
  };
  run_api_runs__run_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        run_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RunDetail"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  samples_api_runs__run_id__samples_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        run_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SampleSummary"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  sample_api_runs__run_id__samples__sample_id__get: {
    parameters: {
      query?: {
        epoch?: number;
      };
      header?: never;
      path: {
        run_id: string;
        sample_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SampleDetail"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  artifact_api_runs__run_id__artifacts__path__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        run_id: string;
        path: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  views_api_runs__run_id__views_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        run_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RunView"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  compare_api_compare_get: {
    parameters: {
      query: {
        a: string;
        b: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Comparison"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  vectors_api_vectors_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Direction"][];
        };
      };
    };
  };
  experiments_api_experiments_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Experiment"][];
        };
      };
    };
  };
  info_api_playground_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PlaygroundInfo"];
        };
      };
    };
  };
  generate_api_playground_generate_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["GenerateRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GenerateResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  inspect_api_playground_inspect_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["InspectRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["InspectResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
}
