/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Health */
    get: operations["health_api_health_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/runs": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Runs */
    get: operations["runs_api_runs_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/runs/{run_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Run */
    get: operations["run_api_runs__run_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/runs/{run_id}/samples": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Samples */
    get: operations["samples_api_runs__run_id__samples_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/runs/{run_id}/samples/{sample_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Sample */
    get: operations["sample_api_runs__run_id__samples__sample_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/runs/{run_id}/artifacts/{path}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Artifact */
    get: operations["artifact_api_runs__run_id__artifacts__path__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/runs/{run_id}/views": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Views */
    get: operations["views_api_runs__run_id__views_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/runs/{run_id}/features": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Feature List */
    get: operations["feature_list_api_runs__run_id__features_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/runs/{run_id}/features/{feature}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Feature */
    get: operations["feature_api_runs__run_id__features__feature__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/compare": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Compare */
    get: operations["compare_api_compare_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/vectors": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Vectors */
    get: operations["vectors_api_vectors_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/graphs": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Graph List */
    get: operations["graph_list_api_graphs_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/experiments": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Experiments */
    get: operations["experiments_api_experiments_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/experiments/{name}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Experiment */
    get: operations["experiment_api_experiments__name__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/playground": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Info */
    get: operations["info_api_playground_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/playground/load": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Load Model
     * @description Replace the model (none unloads it, freeing the GPU for jobs); a bad one is a 400 and
     *     leaves no model loaded.
     */
    post: operations["load_model_api_playground_load_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/playground/generate": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Generate */
    post: operations["generate_api_playground_generate_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/playground/inspect": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Inspect */
    post: operations["inspect_api_playground_inspect_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/playground/patch": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Patch */
    post: operations["patch_api_playground_patch_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/playground/dose": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Dose */
    post: operations["dose_api_playground_dose_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/playground/speed": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Speed */
    post: operations["speed_api_playground_speed_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/launch": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Launchables */
    get: operations["launchables_api_launch_get"];
    put?: never;
    /** Launch */
    post: operations["launch_api_launch_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/launch/options": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Launch Options */
    get: operations["launch_options_api_launch_options_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/launch/jobs": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Job List */
    get: operations["job_list_api_launch_jobs_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/launch/jobs/{job_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Job */
    get: operations["job_api_launch_jobs__job_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/launch/jobs/{job_id}/cancel": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Cancel */
    post: operations["cancel_api_launch_jobs__job_id__cancel_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** Artifact */
    Artifact: {
      /** Path */
      path: string;
      /** Size */
      size: number | null;
    };
    /** Comparison */
    Comparison: {
      /** A */
      a: string;
      /** B */
      b: string;
      /** Only A */
      only_a: number;
      /** Only B */
      only_b: number;
      /** Scores */
      scores: components["schemas"]["PairedScore"][];
    };
    /**
     * Direction
     * @description Where a direction came from and what it is, stored alongside its values.
     */
    Direction: {
      /** Name */
      name: string;
      /** Model */
      model: string;
      /** Layer */
      layer: number;
      /** Method */
      method: string;
      /** Norm */
      norm: number;
      /** Dim */
      dim: number;
      /**
       * Created
       * Format: date-time
       */
      created: string;
      /** Run */
      run?: string | null;
      /** Notes */
      notes?: string | null;
    };
    /**
     * DoseRequest
     * @description A saved direction swept over strengths, read at the next token.
     */
    DoseRequest: {
      /** Prompt */
      prompt: string;
      /** Vector */
      vector: string;
      /** Layer */
      layer?: number | null;
      /** Alphas */
      alphas: number[];
      /** Answer */
      answer: string;
      /** Foil */
      foil?: string | null;
      /**
       * Adapters
       * @default []
       */
      adapters: string[];
      /**
       * Chat
       * @default true
       */
      chat: boolean;
    };
    /** Experiment */
    Experiment: {
      /** Name */
      name: string;
      /**
       * Axis
       * @enum {string}
       */
      axis: "behavior" | "efficiency" | "checks";
      /**
       * Domain
       * @enum {string}
       */
      domain:
        | "mechanisms"
        | "honesty"
        | "conditioning"
        | "agents"
        | "context"
        | "inference"
        | "specialisation"
        | "reproduction";
      /** Domain Title */
      domain_title: string;
      /**
       * Status
       * @enum {string}
       */
      status: "active" | "parked" | "answered";
      /** Question */
      question: string | null;
      /** Result */
      result: string | null;
      /** Runs */
      runs: components["schemas"]["RunSummary"][];
    };
    /** ExperimentDetail */
    ExperimentDetail: {
      /** Name */
      name: string;
      /**
       * Axis
       * @enum {string}
       */
      axis: "behavior" | "efficiency" | "checks";
      /**
       * Domain
       * @enum {string}
       */
      domain:
        | "mechanisms"
        | "honesty"
        | "conditioning"
        | "agents"
        | "context"
        | "inference"
        | "specialisation"
        | "reproduction";
      /** Domain Title */
      domain_title: string;
      /**
       * Status
       * @enum {string}
       */
      status: "active" | "parked" | "answered";
      /** Question */
      question: string | null;
      /** Result */
      result: string | null;
      /** Runs */
      runs: components["schemas"]["RunSummary"][];
      /** Readme */
      readme: string;
    };
    /**
     * FeatureDashboard
     * @description One SAE feature over a dataset, as `loupe features` logs it under features/.
     */
    FeatureDashboard: {
      /** Feature */
      feature: number;
      /** Hook */
      hook: string;
      /** Layer */
      layer: number;
      /** Density */
      density: number;
      /** Max */
      max: number;
      histogram: components["schemas"]["Histogram"];
      /** Promoted */
      promoted: [string, number][];
      /** Suppressed */
      suppressed: [string, number][];
      examples: components["schemas"]["TokensView"];
      /** Neuronpedia */
      neuronpedia?: string | null;
      /** Model */
      model?: string | null;
      /** Sae */
      sae?: string | null;
      /** Sae Id */
      sae_id?: string | null;
    };
    /** GenerateRequest */
    GenerateRequest: {
      /**
       * Interventions
       * @default []
       */
      interventions: {
        [key: string]: unknown;
      }[];
      /**
       * Adapters
       * @description Adapters of the bank live for this request.
       * @default []
       */
      adapters: string[];
      /**
       * Max New Tokens
       * @description Tokens to generate; a diffusion model's reply length.
       * @default 64
       */
      max_new_tokens: number;
      /**
       * Steps
       * @description Denoising steps; the length if unset.
       */
      steps?: number | null;
      /** Prompt */
      prompt: string;
      /**
       * History
       * @description Earlier turns, before prompt: a follow-up such as pushback.
       * @default []
       */
      history: components["schemas"]["Turn"][];
    };
    /**
     * Graph
     * @description One circuit-tracer attribution graph.
     */
    Graph: {
      /** Slug */
      slug: string;
      /** Prompt */
      prompt: string;
      /** Scan */
      scan?: string | null;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /** Health */
    Health: {
      /** Status */
      status: string;
      /** Version */
      version: string;
      /** Home */
      home: string;
      /**
       * Launching
       * @default false
       */
      launching: boolean;
    };
    /** HeatmapView */
    HeatmapView: {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      kind: "heatmap";
      /** Title */
      title: string;
      /** X */
      x: string[];
      /** Y */
      y: string[];
      /** Z */
      z: number[][];
      /** X Label */
      x_label: string;
      /** Y Label */
      y_label: string;
      /** Note */
      note?: string | null;
      /** About */
      about?: string | null;
      /** Slices */
      slices?: {
        [key: string]: number[][];
      } | null;
      /** Labels */
      labels?: string[][] | null;
    };
    /** Histogram */
    Histogram: {
      /** Edges */
      edges: number[];
      /** Counts */
      counts: number[];
    };
    /** InspectRequest */
    InspectRequest: {
      /**
       * Interventions
       * @default []
       */
      interventions: {
        [key: string]: unknown;
      }[];
      /**
       * Adapters
       * @description Adapters of the bank live for this request.
       * @default []
       */
      adapters: string[];
      /**
       * Max New Tokens
       * @description Tokens to generate; a diffusion model's reply length.
       * @default 64
       */
      max_new_tokens: number;
      /**
       * Steps
       * @description Denoising steps; the length if unset.
       */
      steps?: number | null;
      /** Prompt */
      prompt: string;
      /**
       * Vectors
       * @description Saved directions to read, each at its own layer.
       * @default []
       */
      vectors: string[];
      /**
       * Chat
       * @description Wrap the prompt in the model's chat template.
       * @default true
       */
      chat: boolean;
    };
    /** InspectResponse */
    InspectResponse: {
      /** Views */
      views: (
        | components["schemas"]["HeatmapView"]
        | components["schemas"]["LineView"]
        | components["schemas"]["ScatterView"]
        | components["schemas"]["TableView"]
        | components["schemas"]["TokensView"]
      )[];
    };
    /** Job */
    Job: {
      /** Id */
      id: string;
      /** Title */
      title: string;
      /** Argv */
      argv: string[];
      /**
       * Status
       * @default queued
       * @enum {string}
       */
      status: "queued" | "running" | "succeeded" | "failed" | "cancelled";
      /**
       * Created
       * Format: date-time
       */
      created?: string;
      /** Started */
      started?: string | null;
      /** Ended */
      ended?: string | null;
      /** Exit Code */
      exit_code?: number | null;
    };
    /** JobDetail */
    JobDetail: {
      /** Id */
      id: string;
      /** Title */
      title: string;
      /** Argv */
      argv: string[];
      /**
       * Status
       * @default queued
       * @enum {string}
       */
      status: "queued" | "running" | "succeeded" | "failed" | "cancelled";
      /**
       * Created
       * Format: date-time
       */
      created?: string;
      /** Started */
      started?: string | null;
      /** Ended */
      ended?: string | null;
      /** Exit Code */
      exit_code?: number | null;
      /** Log */
      log: string;
    };
    /** LaunchRequest */
    LaunchRequest: {
      /** Id */
      id: string;
      /**
       * Options
       * @default {}
       */
      options: {
        [key: string]: string | boolean | string[];
      };
      /** Config */
      config?: string | null;
      /** Recipe */
      recipe?: string | null;
    };
    /** Launchable */
    Launchable: {
      /** Id */
      id: string;
      /** Group */
      group: string;
      /** Title */
      title: string;
      /**
       * Description
       * @default
       */
      description: string;
      /** Config */
      config?: string | null;
      /** Recipe */
      recipe?: string | null;
    };
    /** LineView */
    LineView: {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      kind: "line";
      /** Title */
      title: string;
      /** X */
      x: number[];
      /** Series */
      series: {
        [key: string]: number[];
      };
      /** X Label */
      x_label: string;
      /** Y Label */
      y_label: string;
      /** Note */
      note?: string | null;
      /** About */
      about?: string | null;
    };
    /**
     * LoadRequest
     * @description A model for the Playground: a Hub id, a path or a name under <home>/models; adapters to load
     *     beside it from <home>/adapters; whether it is a masked diffusion model; its attention kernel
     *     (eager, sdpa, flash_attention_2, flex_attention, a registered name, or file.py:function).
     */
    LoadRequest: {
      /** Model */
      model?: string | null;
      /**
       * Bank
       * @default []
       */
      bank: string[];
      /**
       * Diffusion
       * @default false
       */
      diffusion: boolean;
      /** Attn */
      attn?: string | null;
    };
    /** Message */
    Message: {
      /** Role */
      role: string;
      /** Text */
      text: string;
      /** Tool Calls */
      tool_calls: components["schemas"]["ToolCall"][];
      /**
       * Tool Call Id
       * @description On a tool result: the call it answers.
       */
      tool_call_id?: string | null;
      /** Function */
      function?: string | null;
      /**
       * Error
       * @description On a tool result: the tool's error.
       */
      error?: string | null;
    };
    /** MetricPoint */
    MetricPoint: {
      /** Step */
      step: number;
      /** Value */
      value: number;
    };
    /**
     * Option
     * @description One flag of a command, as its parser declares it.
     */
    Option: {
      /** Flag */
      flag: string;
      /**
       * Kind
       * @enum {string}
       */
      kind: "text" | "bool" | "list" | "choice";
      /** Default */
      default: string | null;
      /**
       * Help
       * @default
       */
      help: string;
      /**
       * Choices
       * @default []
       */
      choices: string[];
      /**
       * Required
       * @default false
       */
      required: boolean;
    };
    /** PairedScore */
    PairedScore: {
      /** Name */
      name: string;
      /** N */
      n: number;
      /** Mean A */
      mean_a: number;
      /** Mean B */
      mean_b: number;
      /**
       * Diff
       * @description Mean of B minus A over paired samples.
       */
      diff: number;
      /**
       * Low
       * @description 95% paired bootstrap interval of diff.
       */
      low: number;
      /** High */
      high: number;
      /**
       * Up
       * @description Samples where B scored higher.
       */
      up: number;
      /** Down */
      down: number;
    };
    /**
     * PatchRequest
     * @description Which layer, position or head carries the difference between two prompts of one length.
     */
    PatchRequest: {
      /** Clean */
      clean: string;
      /** Corrupt */
      corrupt: string;
      /**
       * Answer
       * @description The clean prompt's next token.
       */
      answer: string;
      /**
       * Foil
       * @description The corrupt prompt's next token.
       */
      foil: string;
      /**
       * Method
       * @default attribution
       * @enum {string}
       */
      method: "attribution" | "residual" | "heads";
      /**
       * Adapters
       * @default []
       */
      adapters: string[];
      /**
       * Chat
       * @default true
       */
      chat: boolean;
    };
    /** PlaygroundInfo */
    PlaygroundInfo: {
      /** Model */
      model: string | null;
      /** Layers */
      layers: number | null;
      /** Heads */
      heads?: number | null;
      /**
       * Bank
       * @default []
       */
      bank: string[];
      /**
       * Diffusion
       * @default false
       */
      diffusion: boolean;
      /**
       * Switchable
       * @default false
       */
      switchable: boolean;
    };
    /** RunDetail */
    RunDetail: {
      /** Id */
      id: string;
      /**
       * Kind
       * @enum {string}
       */
      kind: "eval" | "analysis" | "training";
      /** Name */
      name: string;
      /** Experiment */
      experiment: string | null;
      /** Status */
      status: string;
      /** Created */
      created: string | null;
      /** Model */
      model: string | null;
      /** Metrics */
      metrics: {
        [key: string]: number;
      };
      /** Samples */
      samples: number | null;
      /** Total */
      total?: number | null;
      /** Params */
      params: {
        [key: string]: string;
      };
      /** Tags */
      tags: {
        [key: string]: string;
      };
      /** History */
      history: {
        [key: string]: components["schemas"]["MetricPoint"][];
      };
      /** Artifacts */
      artifacts: components["schemas"]["Artifact"][];
      /** Scorers */
      scorers: string[];
      /** Error */
      error: string | null;
      /** Log */
      log?: string | null;
    };
    /** RunSummary */
    RunSummary: {
      /** Id */
      id: string;
      /**
       * Kind
       * @enum {string}
       */
      kind: "eval" | "analysis" | "training";
      /** Name */
      name: string;
      /** Experiment */
      experiment: string | null;
      /** Status */
      status: string;
      /** Created */
      created: string | null;
      /** Model */
      model: string | null;
      /** Metrics */
      metrics: {
        [key: string]: number;
      };
      /** Samples */
      samples: number | null;
      /** Total */
      total?: number | null;
    };
    /**
     * RunView
     * @description A figure a run logged under views/, addressed by its artifact path.
     */
    RunView: {
      /** Path */
      path: string;
      /** View */
      view:
        | components["schemas"]["HeatmapView"]
        | components["schemas"]["LineView"]
        | components["schemas"]["ScatterView"]
        | components["schemas"]["TableView"]
        | components["schemas"]["TokensView"];
    };
    /** SampleDetail */
    SampleDetail: {
      /** Id */
      id: string;
      /** Epoch */
      epoch: number;
      /** Target */
      target: string;
      /** Messages */
      messages: components["schemas"]["Message"][];
      /** Scores */
      scores: components["schemas"]["Score"][];
      /** Metadata */
      metadata: {
        [key: string]: string;
      };
      /** Error */
      error: string | null;
    };
    /** SampleSummary */
    SampleSummary: {
      /** Id */
      id: string;
      /** Epoch */
      epoch: number;
      /** Input */
      input: string;
      /** Target */
      target: string;
      /** Scores */
      scores: {
        [key: string]: number | null;
      };
      /** Error */
      error: string | null;
    };
    /** ScatterPoint */
    ScatterPoint: {
      /** Label */
      label: string;
      /** X */
      x: number;
      /** Y */
      y: number;
    };
    /** ScatterView */
    ScatterView: {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      kind: "scatter";
      /** Title */
      title: string;
      /** Points */
      points: components["schemas"]["ScatterPoint"][];
      /** X Label */
      x_label: string;
      /** Y Label */
      y_label: string;
      /** Note */
      note?: string | null;
      /** About */
      about?: string | null;
    };
    /** Score */
    Score: {
      /** Name */
      name: string;
      /** Value */
      value: number | null;
      /** Raw */
      raw: string;
      /** Answer */
      answer: string | null;
      /** Explanation */
      explanation: string | null;
    };
    /**
     * SpeedRequest
     * @description The prompt timed base and, with interventions or adapters, changed.
     */
    SpeedRequest: {
      /**
       * Interventions
       * @default []
       */
      interventions: {
        [key: string]: unknown;
      }[];
      /**
       * Adapters
       * @description Adapters of the bank live for this request.
       * @default []
       */
      adapters: string[];
      /**
       * Max New Tokens
       * @description Tokens to generate; a diffusion model's reply length.
       * @default 64
       */
      max_new_tokens: number;
      /**
       * Steps
       * @description Denoising steps; the length if unset.
       */
      steps?: number | null;
      /** Prompt */
      prompt: string;
      /**
       * Repeats
       * @default 3
       */
      repeats: number;
    };
    /** TableView */
    TableView: {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      kind: "table";
      /** Title */
      title: string;
      /** Columns */
      columns: string[];
      /** Rows */
      rows: (string | number | boolean | null)[][];
      /** Note */
      note?: string | null;
      /** About */
      about?: string | null;
      /** Links */
      links?: (string | null)[][] | null;
      /** Embed */
      embed?: "neuronpedia" | null;
    };
    /** TokenRow */
    TokenRow: {
      /** Tokens */
      tokens: string[];
      /** Values */
      values: {
        [key: string]: number[];
      };
      /** Label */
      label?: string | null;
    };
    /** TokensView */
    TokensView: {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      kind: "tokens";
      /** Title */
      title: string;
      /** Rows */
      rows: components["schemas"]["TokenRow"][];
      /** Pairs */
      pairs?: {
        [key: string]: number[][];
      } | null;
      /** Note */
      note?: string | null;
      /** About */
      about?: string | null;
    };
    /** ToolCall */
    ToolCall: {
      /**
       * Id
       * @default
       */
      id: string;
      /** Function */
      function: string;
      /**
       * Arguments
       * @description The arguments as indented JSON.
       */
      arguments: string;
      /** Parse Error */
      parse_error?: string | null;
    };
    /** Turn */
    Turn: {
      /**
       * Role
       * @enum {string}
       */
      role: "user" | "assistant";
      /** Content */
      content: string;
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
      /** Input */
      input?: unknown;
      /** Context */
      ctx?: Record<string, never>;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  health_api_health_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Health"];
        };
      };
    };
  };
  runs_api_runs_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RunSummary"][];
        };
      };
    };
  };
  run_api_runs__run_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        run_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RunDetail"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  samples_api_runs__run_id__samples_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        run_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SampleSummary"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  sample_api_runs__run_id__samples__sample_id__get: {
    parameters: {
      query?: {
        epoch?: number;
      };
      header?: never;
      path: {
        run_id: string;
        sample_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SampleDetail"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  artifact_api_runs__run_id__artifacts__path__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        run_id: string;
        path: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  views_api_runs__run_id__views_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        run_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RunView"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  feature_list_api_runs__run_id__features_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        run_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": number[];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  feature_api_runs__run_id__features__feature__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        run_id: string;
        feature: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["FeatureDashboard"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  compare_api_compare_get: {
    parameters: {
      query: {
        a: string;
        b: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Comparison"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  vectors_api_vectors_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Direction"][];
        };
      };
    };
  };
  graph_list_api_graphs_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Graph"][];
        };
      };
    };
  };
  experiments_api_experiments_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Experiment"][];
        };
      };
    };
  };
  experiment_api_experiments__name__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        name: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ExperimentDetail"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  info_api_playground_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PlaygroundInfo"];
        };
      };
    };
  };
  load_model_api_playground_load_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["LoadRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PlaygroundInfo"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  generate_api_playground_generate_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["GenerateRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "text/plain": string;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  inspect_api_playground_inspect_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["InspectRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["InspectResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  patch_api_playground_patch_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PatchRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["InspectResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  dose_api_playground_dose_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["DoseRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["InspectResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  speed_api_playground_speed_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SpeedRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["InspectResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  launchables_api_launch_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Launchable"][];
        };
      };
    };
  };
  launch_api_launch_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["LaunchRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Job"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  launch_options_api_launch_options_get: {
    parameters: {
      query: {
        id: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Option"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  job_list_api_launch_jobs_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Job"][];
        };
      };
    };
  };
  job_api_launch_jobs__job_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        job_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["JobDetail"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  cancel_api_launch_jobs__job_id__cancel_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        job_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Job"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
}
