/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Health */
    get: operations["health_api_health_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/runs": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Runs */
    get: operations["runs_api_runs_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/runs/{run_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Run */
    get: operations["run_api_runs__run_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/runs/{run_id}/samples": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Samples */
    get: operations["samples_api_runs__run_id__samples_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/runs/{run_id}/samples/{sample_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Sample */
    get: operations["sample_api_runs__run_id__samples__sample_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/runs/{run_id}/artifacts/{path}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Artifact */
    get: operations["artifact_api_runs__run_id__artifacts__path__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/experiments": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Experiments */
    get: operations["experiments_api_experiments_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** Artifact */
    Artifact: {
      /** Path */
      path: string;
      /** Size */
      size: number | null;
    };
    /** Experiment */
    Experiment: {
      /** Name */
      name: string;
      /** Question */
      question: string | null;
      /** Runs */
      runs: components["schemas"]["RunSummary"][];
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /** Health */
    Health: {
      /** Status */
      status: string;
      /** Version */
      version: string;
      /** Home */
      home: string;
    };
    /** Message */
    Message: {
      /** Role */
      role: string;
      /** Text */
      text: string;
      /** Tool Calls */
      tool_calls: components["schemas"]["ToolCall"][];
    };
    /** MetricPoint */
    MetricPoint: {
      /** Step */
      step: number;
      /** Value */
      value: number;
    };
    /** RunDetail */
    RunDetail: {
      /** Id */
      id: string;
      /**
       * Kind
       * @enum {string}
       */
      kind: "eval" | "analysis" | "training";
      /** Name */
      name: string;
      /** Experiment */
      experiment: string | null;
      /** Status */
      status: string;
      /** Created */
      created: string | null;
      /** Model */
      model: string | null;
      /** Metrics */
      metrics: {
        [key: string]: number;
      };
      /** Samples */
      samples: number | null;
      /** Params */
      params: {
        [key: string]: string;
      };
      /** Tags */
      tags: {
        [key: string]: string;
      };
      /** History */
      history: {
        [key: string]: components["schemas"]["MetricPoint"][];
      };
      /** Artifacts */
      artifacts: components["schemas"]["Artifact"][];
      /** Scorers */
      scorers: string[];
      /** Error */
      error: string | null;
    };
    /** RunSummary */
    RunSummary: {
      /** Id */
      id: string;
      /**
       * Kind
       * @enum {string}
       */
      kind: "eval" | "analysis" | "training";
      /** Name */
      name: string;
      /** Experiment */
      experiment: string | null;
      /** Status */
      status: string;
      /** Created */
      created: string | null;
      /** Model */
      model: string | null;
      /** Metrics */
      metrics: {
        [key: string]: number;
      };
      /** Samples */
      samples: number | null;
    };
    /** SampleDetail */
    SampleDetail: {
      /** Id */
      id: string;
      /** Epoch */
      epoch: number;
      /** Target */
      target: string;
      /** Messages */
      messages: components["schemas"]["Message"][];
      /** Scores */
      scores: components["schemas"]["Score"][];
      /** Metadata */
      metadata: {
        [key: string]: string;
      };
      /** Error */
      error: string | null;
    };
    /** SampleSummary */
    SampleSummary: {
      /** Id */
      id: string;
      /** Epoch */
      epoch: number;
      /** Input */
      input: string;
      /** Target */
      target: string;
      /** Scores */
      scores: {
        [key: string]: number | null;
      };
      /** Error */
      error: string | null;
    };
    /** Score */
    Score: {
      /** Name */
      name: string;
      /** Value */
      value: number | null;
      /** Raw */
      raw: string;
      /** Answer */
      answer: string | null;
      /** Explanation */
      explanation: string | null;
    };
    /** ToolCall */
    ToolCall: {
      /** Function */
      function: string;
      /** Arguments */
      arguments: string;
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
      /** Input */
      input?: unknown;
      /** Context */
      ctx?: Record<string, never>;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  health_api_health_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Health"];
        };
      };
    };
  };
  runs_api_runs_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RunSummary"][];
        };
      };
    };
  };
  run_api_runs__run_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        run_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RunDetail"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  samples_api_runs__run_id__samples_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        run_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SampleSummary"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  sample_api_runs__run_id__samples__sample_id__get: {
    parameters: {
      query?: {
        epoch?: number;
      };
      header?: never;
      path: {
        run_id: string;
        sample_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SampleDetail"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  artifact_api_runs__run_id__artifacts__path__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        run_id: string;
        path: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  experiments_api_experiments_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Experiment"][];
        };
      };
    };
  };
}
